"""Deterministic PDF table/chart helpers for the Chainlit AI PDF Chatbot.

The module intentionally keeps extraction conservative: it only reports values
that can be read from the PDF itself and never fabricates missing data.
"""
from __future__ import annotations

import io
import re
from typing import Any

import pandas as pd
import pdfplumber
import pymupdf

REFUSAL_NO_TABLE = {
    "English": "I could not find enough machine-readable table data in the PDF to answer that.",
    "Urdu": "مجھے PDF میں اتنا قابلِ مطالعہ جدول کا ڈیٹا نہیں ملا کہ اس کا جواب دے سکوں۔",
    "Roman Urdu": "Mujhe PDF mein itna qabil-e-mutala table data nahi mila ke iska jawab de sakun.",
    "Arabic": "لم أجد في ملف PDF بيانات جدولية قابلة للقراءة بما يكفي للإجابة عن ذلك.",
}


def _norm(text: Any) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip().lower()


def looks_like_table_question(query: str) -> bool:
    q = _norm(query)
    hints = (
        "table", "tabular", "row", "column", "columns", "rows", "cell",
        "average", "mean", "median", "sum", "total", "highest", "lowest",
        "maximum", "minimum", "compare", "data", "جدول", "قطار", "کالم",
        "table dikhao", "data dikhao", "جدول دکھاؤ", "جدول دکھائیں",
        "جدول", "الجدول",
    )
    return any(h in q for h in hints)


def looks_like_chart_question(query: str) -> bool:
    q = _norm(query)
    hints = (
        "chart", "graph", "plot", "figure", "bar chart", "line chart",
        "pie chart", "histogram", "trend", "x-axis", "y-axis", "x axis",
        "y axis", "graph mein", "chart mein", "گراف", "چارٹ", "نمودار",
        "المخطط", "الرسم البياني",
    )
    return any(h in q for h in hints)


_SPECIFIC_CHART_TYPE_WORDS = (
    "bar chart", "pie chart", "donut chart", "doughnut chart", "line chart",
    "scatter", "histogram", "area chart", "combination chart",
    "بار چارٹ", "پائی چارٹ",
)


def looks_like_all_charts_request(query: str) -> bool:
    q = _norm(query)
    # If the question names ONE specific chart type ("the pie chart", "bar
    # chart data"), that's a targeted question about that single chart —
    # never treat it as "analyze every chart", even if it also contains a
    # generic word like "data" or "chart" elsewhere in the sentence.
    if any(t in q for t in _SPECIFIC_CHART_TYPE_WORDS):
        return False
    hints = (
        "all chart", "every chart", "all charts", "all graphs", "all figures",
        "analyze all chart", "summarize all chart", "give me all chart",
        "all chart data", "all the charts", "all the graphs",
        "sab chart", "har chart", "saare chart", "har graph", "sab graph",
        "sab charts ka data", "har chart ka data",
    )
    return any(h in q for h in hints)


def _clean_table(raw: list[list[Any]] | None) -> pd.DataFrame | None:
    if not raw:
        return None
    rows = []
    for row in raw:
        if row is None:
            continue
        cleaned = ["" if cell is None else str(cell).replace("\n", " ").strip() for cell in row]
        if any(cleaned):
            rows.append(cleaned)
    if len(rows) < 2:
        return None

    width = max(len(r) for r in rows)
    rows = [r + [""] * (width - len(r)) for r in rows]
    header = rows[0]
    if not any(header):
        header = [f"Column {i + 1}" for i in range(width)]
        data = rows
    else:
        data = rows[1:]
    # Make duplicate/blank headers safe for pandas and markdown rendering.
    seen: dict[str, int] = {}
    columns = []
    for i, name in enumerate(header):
        base = name or f"Column {i + 1}"
        seen[base] = seen.get(base, 0) + 1
        columns.append(base if seen[base] == 1 else f"{base} ({seen[base]})")
    df = pd.DataFrame(data, columns=columns)
    # Drop completely empty columns/rows generated by PDF table borders.
    df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")
    return df if not df.empty else None


def extract_tables(path: str) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []
    try:
        with pdfplumber.open(path) as pdf:
            for page_number, page in enumerate(pdf.pages, start=1):
                try:
                    tables = page.extract_tables() or []
                except Exception:
                    tables = []
                for table_index, raw in enumerate(tables, start=1):
                    df = _clean_table(raw)
                    if df is not None and len(df.columns) >= 2 and len(df) >= 1:
                        found.append({
                            "page": page_number,
                            "page_range": (page_number, page_number),
                            "table_index": table_index,
                            "dataframe": df,
                        })
    except Exception:
        return []
    return _stitch_multipage_tables(found)


def _stitch_multipage_tables(tables: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Merge a table that continues onto the next page (same column headers,
    consecutive page numbers, the earlier one being the last table on its
    page) into a single logical table spanning both pages — otherwise
    'average revenue' etc. would silently only see half the rows."""
    if len(tables) < 2:
        return tables
    merged: list[dict[str, Any]] = []
    for item in tables:
        if merged:
            prev = merged[-1]
            prev_df = prev["dataframe"]
            cur_df = item["dataframe"]
            same_columns = list(prev_df.columns) == list(cur_df.columns)
            consecutive_pages = item["page"] == prev["page_range"][1] + 1
            if same_columns and consecutive_pages:
                prev["dataframe"] = pd.concat([prev_df, cur_df], ignore_index=True)
                prev["page_range"] = (prev["page_range"][0], item["page"])
                continue
        merged.append(dict(item))
    return merged


def ocr_scanned_page(path: str, page_number: int, vision_call) -> str:
    """Best-effort OCR fallback for a scanned PDF page with no selectable
    text, reusing the same Gemini vision call already used for charts —
    intentionally avoids adding a separate OCR dependency (pytesseract/etc)."""
    try:
        doc = pymupdf.open(path)
        try:
            page = doc.load_page(page_number - 1)
            pix = page.get_pixmap(matrix=pymupdf.Matrix(2.0, 2.0), alpha=False)
            image_bytes = pix.tobytes("png")
        finally:
            doc.close()
        prompt = (
            "This PDF page is a scanned image with no selectable text. Transcribe "
            "ALL readable text on this page as plain text, in natural reading order. "
            "Output ONLY the transcribed text — no commentary, no markdown. "
            "If nothing is legible, output exactly: NO_TEXT_FOUND"
        )
        text = (vision_call(image_bytes, prompt) or "").strip()
        if not text or text.upper() == "NO_TEXT_FOUND":
            return ""
        return text
    except Exception as exc:
        print(f"[ocr] scanned-page OCR failed (page {page_number}): {exc}")
        return ""


def _numeric_series(series: pd.Series) -> pd.Series:
    cleaned = series.astype(str).str.replace(r"[^0-9.\-]", "", regex=True)
    return pd.to_numeric(cleaned, errors="coerce")


# Public alias so callers outside this module (app.py) don't reach into a
# "private" underscored name just to reuse the same numeric-cleaning logic.
numeric_series = _numeric_series


def _find_column(df: pd.DataFrame, query: str) -> str | None:
    q = _norm(query)
    for col in df.columns:
        if _norm(col) in q or q in _norm(col):
            return col
    return None


FIELD_ALIASES = {
    "salary": ("salary", "pay", "wage", "income", "compensation", "earnings"),
    "age": ("age", "years old"),
    "score": ("score", "marks", "grade", "points", "rating"),
    "price": ("price", "cost", "amount", "rate"),
    "quantity": ("quantity", "qty", "count", "units", "number"),
}
FIELD_FILE_HINTS = {
    "salary": ("employee", "staff", "payroll", "salary", "worker", "job"),
    "price": ("product", "item", "catalog", "price"),
    "score": ("score", "result", "exam", "student", "grade"),
}


def _requested_field(query: str) -> str | None:
    q = _norm(query)
    for field, aliases in FIELD_ALIASES.items():
        if any(alias in q for alias in aliases):
            return field
    return None


def _column_match_score(column: str, query: str, requested_field: str | None) -> int:
    name = _norm(column)
    q = _norm(query)
    score = 0
    if name and name in q:
        score += 100
    if requested_field:
        aliases = FIELD_ALIASES[requested_field]
        if any(alias in name or name in alias for alias in aliases):
            score += 80
    return score


_TABLE_ORDINAL_WORDS = {
    "first": 1, "1st": 1, "table 1": 1, "table one": 1, "pehla": 1, "pehli": 1,
    "second": 2, "2nd": 2, "table 2": 2, "table two": 2, "doosra": 2, "dusra": 2, "doosri": 2,
    "third": 3, "3rd": 3, "table 3": 3, "table three": 3, "teesra": 3, "tisra": 3,
    "fourth": 4, "4th": 4, "table 4": 4, "table four": 4, "chotha": 4,
    "fifth": 5, "5th": 5, "table 5": 5, "table five": 5,
}


def _requested_table_ordinal(query: str) -> int | None:
    """Detects an explicit reference like 'table 2', 'second table', 'doosra
    table' so that request can go straight to that table instead of
    whichever table happens to score highest on column-name relevance
    (which was always resolving to the same table when the question didn't
    name a specific field)."""
    q = _norm(query)
    m = re.search(r"table\s*(?:no\.?|number|#)?\s*(\d+)", q)
    if m:
        return int(m.group(1))
    for phrase, ordinal in _TABLE_ORDINAL_WORDS.items():
        if phrase in q:
            return ordinal
    return None


def relevant_tables(query: str, tables: list[dict[str, Any]], max_tables: int = 3) -> list[dict[str, Any]]:
    """Return the most query-relevant extracted tables with their PDF/page provenance."""
    if not tables:
        return []

    ordinal = _requested_table_ordinal(query)
    if ordinal and 1 <= ordinal <= len(tables):
        # Explicit "table 2" / "second table" reference — honor it directly
        # rather than letting column-name relevance scoring (which defaults
        # to the same top table when no field keyword matches) override it.
        return [tables[ordinal - 1]]

    q = _norm(query)
    field = _requested_field(q)
    scored = []
    for idx, item in enumerate(tables):
        df = item.get("dataframe")
        if df is None or df.empty:
            continue
        score = 0
        for col in df.columns:
            score = max(score, _column_match_score(str(col), q, field))
        filename = _norm(item.get("pdf_path", ""))
        if field and field in filename:
            score += 15
        if field:
            score += sum(4 for hint in FIELD_FILE_HINTS.get(field, ()) if hint in filename)
        numeric_cells = sum(int(_numeric_series(df[c]).notna().sum()) for c in df.columns)
        score += min(numeric_cells, 10)
        scored.append((score, idx, item))
    scored.sort(key=lambda x: (-x[0], x[1]))
    return [item for _, _, item in scored[:max_tables]]


def answer_table_query(query: str, tables: list[dict[str, Any]], language: str = "English") -> str:
    if not tables:
        return REFUSAL_NO_TABLE.get(language, REFUSAL_NO_TABLE["English"])

    q = _norm(query)
    if any(x in q for x in ("show table", "display table", "table dikhao", "data dikhao", "جدول دکھ")):
        return "I found table data in the PDF."

    aggregate = None
    if any(x in q for x in ("average", "mean", "avg")):
        aggregate = "mean"
    elif "median" in q:
        aggregate = "median"
    elif any(x in q for x in ("sum", "total", "add up")):
        aggregate = "sum"
    elif any(x in q for x in ("highest", "maximum", "max", "largest")):
        aggregate = "max"
    elif any(x in q for x in ("lowest", "minimum", "min", "smallest")):
        aggregate = "min"

    if not aggregate:
        return ""

    requested_field = _requested_field(q)
    candidates_by_table = []
    for item in relevant_tables(q, tables, max_tables=len(tables)):
        df = item.get("dataframe")
        if df is None or df.empty:
            continue
        candidates = []
        for col in df.columns:
            nums = _numeric_series(df[col]).dropna()
            if len(nums):
                candidates.append((col, nums, _column_match_score(str(col), q, requested_field)))
        if candidates:
            candidates_by_table.append((max(x[2] for x in candidates), item, candidates))

    if not candidates_by_table:
        return REFUSAL_NO_TABLE.get(language, REFUSAL_NO_TABLE["English"])

    candidates_by_table.sort(key=lambda x: -x[0])
    _, item, candidates = candidates_by_table[0]
    col, nums, _ = max(candidates, key=lambda x: (x[2], len(x[1])))
    value = {"mean": nums.mean(), "median": nums.median(), "sum": nums.sum(), "max": nums.max(), "min": nums.min()}[aggregate]

    # Do not expose extraction artifacts such as "Column 2" when the user asked
    # for a semantic field such as salary.
    display_col = requested_field or str(col)
    if str(col).lower().startswith("column ") and requested_field:
        display_col = requested_field

    if language == "Urdu":
        labels = {"mean": "اوسط", "median": "میڈین", "sum": "کل", "max": "زیادہ سے زیادہ", "min": "کم سے کم"}
        return f"{labels[aggregate]} ({display_col}): {value:g} — صفحہ {item['page']}۔"
    if language == "Roman Urdu":
        labels = {"mean": "Average", "median": "Median", "sum": "Total", "max": "Maximum", "min": "Minimum"}
        return f"{labels[aggregate]} ({display_col}): {value:g} — page {item['page']}."
    if language == "Arabic":
        labels = {"mean": "المتوسط", "median": "الوسيط", "sum": "المجموع", "max": "الحد الأقصى", "min": "الحد الأدنى"}
        return f"{labels[aggregate]} ({display_col}): {value:g} — الصفحة {item['page']}."
    labels = {"mean": "Average", "median": "Median", "sum": "Total", "max": "Maximum", "min": "Minimum"}
    return f"{labels[aggregate]} ({display_col}): {value:g} — page {item['page']}."

def find_chart_pages(path: str) -> list[int]:
    """Rank pages by how likely they are to contain an actual chart/figure.
    Deliberately conservative: a page only qualifies if it has an embedded
    raster image (how matplotlib/etc. save a chart into a PDF) or BOTH a
    chart-ish caption AND heavy vector art. Neither a caption word alone
    (ordinary text can say "trend"/"figure") nor a high drawing count alone
    (table borders/fills also produce many small drawings) is enough by
    itself — that combination previously caused plain data-table pages to
    be misidentified as charts, and a table then being "helpfully"
    summarized by the vision model as if it were the requested chart."""
    scored: list[tuple[int, int]] = []  # (score, page_number)
    try:
        doc = pymupdf.open(path)
        try:
            for idx, page in enumerate(doc, start=1):
                page_area = max(page.rect.width * page.rect.height, 1)
                try:
                    image_infos = page.get_image_info()
                except Exception:
                    image_infos = []
                # Only count a LARGE embedded image as a chart signal — a
                # small logo/letterhead/watermark image (common on formal
                # documents) is not a chart and was previously enough by
                # itself to misflag a plain table page as a "chart page".
                large_images = []
                for info in image_infos:
                    bbox = info.get("bbox")
                    if not bbox:
                        continue
                    x0, y0, x1, y1 = bbox
                    area = max(x1 - x0, 0) * max(y1 - y0, 0)
                    if area / page_area >= 0.12:
                        large_images.append(info)

                drawings = page.get_drawings()
                text = page.get_text("text")
                # A REAL chart caption looks like "Chart 1:", "Figure 2." —
                # matching the bare word "chart"/"figure" anywhere on the
                # page was too loose: ordinary prose (e.g. an intro sentence
                # saying "this document contains tables, charts and text")
                # would match and, combined with a table's border-line
                # count, misflag a plain table-only page as a chart page.
                has_caption = bool(re.search(
                    r"\b(chart|figure|graph|plot|نمودار|گراف|چارٹ)\s*[\d:.\-]",
                    text, re.IGNORECASE,
                ))
                heavy_drawing = len(drawings) >= 40

                score = 0
                if large_images:
                    score += 100  # a sizeable embedded picture is by far the strongest signal
                elif has_caption and heavy_drawing:
                    score += 40  # native vector chart: needs BOTH signals together
                if large_images and has_caption:
                    score += 20  # extra confidence boost, not required

                if score > 0:
                    scored.append((score, idx))
        finally:
            doc.close()
    except Exception:
        return []
    scored.sort(key=lambda x: (-x[0], x[1]))
    return [page_number for _, page_number in scored[:6]]


def _friendly_vision_error(exc: Exception) -> str:
    """Chart/vision calls used to fail silently with a generic 'could not
    extract' message even when the REAL cause was something like the
    Gemini free-tier daily quota being exhausted — which looks exactly like
    a detection failure to the user but is actually an API/billing limit."""
    text = str(exc)
    if "RESOURCE_EXHAUSTED" in text or "429" in text or "quota" in text.lower():
        return (
            "⚠️ Gemini API usage limit reached (quota exhausted) — this is an "
            "account/billing limit on the API key, not a chart-detection failure. "
            "Wait for the daily quota to reset, or check your plan at "
            "https://ai.google.dev/gemini-api/docs/rate-limits."
        )
    return f"Vision request failed: {text}"


_NEGATIVE_VISION_HINTS = (
    "no chart", "not present", "does not show", "doesn't show", "no graph",
    "no figure", "not visible", "not found", "no pie chart", "no bar chart",
    "no line chart", "not readable", "unable to find", "could not find",
)


def _looks_like_negative_vision_reply(answer: str) -> bool:
    a = _norm(answer)
    return any(hint in a for hint in _NEGATIVE_VISION_HINTS)


def answer_chart_query(query: str, path: str, pages: list[int], language: str, vision_call) -> tuple[str, int | None]:
    """Returns (answer, page_number_actually_used) — the page actually used
    for citation purposes may not be the first candidate, since a page can
    be skipped if it turned out not to have the relevant chart."""
    if not pages:
        return REFUSAL_NO_TABLE.get(language, REFUSAL_NO_TABLE["English"]), None
    q = _norm(query)
    named_type = next((t.split()[0] for t in _SPECIFIC_CHART_TYPE_WORDS if t in q and "چارٹ" not in t), None)
    type_instruction = (
        f'The user specifically asked about the {named_type.upper()} chart. If this '
        f"page's chart is a DIFFERENT type (e.g. it's a bar chart but a pie chart was "
        f"asked for), reply with exactly: NOT_ON_THIS_PAGE — even if this page has some "
        f"other chart on it."
        if named_type else ""
    )
    try:
        doc = pymupdf.open(path)
    except Exception:
        return "I found likely chart/figure page(s), but could not reliably extract the requested value from any of them.", None

    last_error: Exception | None = None
    try:
        for page_number in pages[:6]:
            try:
                page = doc.load_page(page_number - 1)
                pix = page.get_pixmap(matrix=pymupdf.Matrix(1.5, 1.5), alpha=False)
                image_bytes = pix.tobytes("png")
                prompt = f"""Read this PDF page image to answer the user's chart/graph question.
First check: is this page an actual VISUAL chart/graph/figure (bars, lines, pie
slices, scatter points, etc.)? A plain table of text/numbers in rows and
columns is NOT a chart, even if it contains the same kind of data — if this
page is a data table rather than a visual chart, reply with exactly:
NOT_ON_THIS_PAGE
Use ONLY information visibly readable in the image — never guess or invent numbers.
If a value is printed exactly on the chart, state it as-is. If you must visually
estimate a value from the axis/bar position (no printed number), prefix it with
"Approximately" and never present it as exact.
{type_instruction}
If this specific page has no chart/graph relevant to the question, reply with
exactly: NOT_ON_THIS_PAGE
Question: {query}
Answer in: {language}
"""
                answer = (vision_call(image_bytes, prompt) or "").strip()
            except Exception as exc:
                # One page failing (a transient API error, a decode issue,
                # etc.) must not abort checking the OTHER candidate pages —
                # this used to be one try/except around the whole loop, so a
                # single bad page silently killed the entire chart answer.
                # We DO remember the error though: if every page fails the
                # same way (e.g. API quota exhausted), that's the real
                # answer to surface, not a generic "not found".
                last_error = exc
                print(f"[chart] page {page_number} failed, trying next candidate: {exc}")
                continue
            if not answer:
                continue
            # This page wasn't the right one — try the next candidate
            # instead of confidently reporting a negative result from
            # what might just be the wrong page of the PDF.
            if "NOT_ON_THIS_PAGE" in answer.upper() or _looks_like_negative_vision_reply(answer):
                continue
            return answer + f" — page {page_number}.", page_number
    finally:
        doc.close()

    if last_error is not None:
        return _friendly_vision_error(last_error), None
    return "I found likely chart/figure page(s), but could not reliably extract the requested value from any of them.", None


_CHART_BREAKDOWN_PROMPT = """You are reading ONE page image from a PDF that may contain a chart, graph, or figure.

First check: is this page an actual VISUAL chart/graph/figure (bars, lines, pie
slices, scatter points, etc.)? A plain table of text/numbers in rows and columns
is NOT a chart, even if it contains similar data.

If this page has NO visual chart/graph/figure at all (including if it's just a
data table), reply with exactly one line: NO_CHART_ON_PAGE

Otherwise, using ONLY what is visibly readable on the page — never invent data — reply in {language} with this exact structure:

**Title:** <chart title, or "No title visible">
**Type:** <bar / line / pie / donut / scatter / histogram / combination / area / other>

**Extracted data:**
<a small Markdown table reconstructing the data: categories/x-axis in the first column,
each data series as a further column. If a cell's value cannot be reliably read, write
"N/A" — never guess. Prefix any visually-estimated (not printed) value with "~".>

**Summary:** <1-2 sentence plain-language summary of what the chart shows>
**Key insights:**
- <highest value/category>
- <lowest value/category>
- <overall trend, if visible>
"""


def analyze_all_charts(path: str, pages: list[int], language: str, vision_call, max_pages: int = 4) -> str:
    """Structured page-by-page breakdown of every detected chart page,
    each converted into a real table + summary + insights, with its PDF
    page number — used for 'analyze/summarize/give me all chart data'."""
    if not pages:
        return REFUSAL_NO_TABLE.get(language, REFUSAL_NO_TABLE["English"])

    sections = []
    inspected_pages = pages[:max_pages]
    last_error: Exception | None = None
    try:
        doc = pymupdf.open(path)
        try:
            for page_number in inspected_pages:
                try:
                    page = doc.load_page(page_number - 1)
                    pix = page.get_pixmap(matrix=pymupdf.Matrix(1.6, 1.6), alpha=False)
                    image_bytes = pix.tobytes("png")
                    prompt = _CHART_BREAKDOWN_PROMPT.format(language=language)
                    result = (vision_call(image_bytes, prompt) or "").strip()
                except Exception as exc:
                    last_error = exc
                    print(f"[chart] analyze_all_charts: page {page_number} failed: {exc}")
                    continue
                if not result or "NO_CHART_ON_PAGE" in result.upper():
                    continue
                sections.append(f"### Chart — page {page_number}\n\n{result}")
        finally:
            doc.close()
    except Exception as exc:
        last_error = exc
        print(f"[chart] analyze_all_charts failed: {exc}")

    if not sections:
        if last_error is not None:
            return _friendly_vision_error(last_error)
        return REFUSAL_NO_TABLE.get(language, REFUSAL_NO_TABLE["English"])

    note = ""
    if len(pages) > max_pages:
        note = f"\n\n*(Inspected the {max_pages} most likely chart pages out of {len(pages)} candidates found, to keep this response fast.)*"
    return "\n\n---\n\n".join(sections) + note